services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
    depends_on:
      - db
    volumes:
      - ./server.js:/app/server.js
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
